// webmake: ignore
//
// DO NOT EDIT. FILE WAS AUTOGENERATED
// GENERATION TIMESTAMP: $TIME$

'use strict';

var getObject = require('dbjs/lib/objects')._get
  , Event     = require('dbjs/lib/event')
  , load      = require('dbjs/lib/signal')._add

  , now = Date.now

  , time;

module.exports = require('dbjs');

//$LOG$time = now();

$IMPORT$

//$LOG$console.log("Schema restore: $COUNT$ objects in " +
//$LOG$	((now() - time) / 1000).toFixed(3) + "s");
