// webmake: ignore
//
// DO NOT EDIT. FILE WAS AUTOGENERATED
// GENERATION TIMESTAMP: $TIME$

'use strict';

var getObject = require('dbjs/lib/objects')._get

  , defineProperty = Object.defineProperty
  , value = { value: true, enumerable: false, configurable: true,
		writable: true };

//$LOG$process.stdout.write("Setup '$TAG$' tags...");

$CONTENT$

//$LOG$process.stdout.write(" Done [$COUNT$ tags]\n");
